version: '3.8'

services:
  ollama:
    build:
     context: ./ollama
     args:
       TEXT_EMBEDDINGS_MODEL: ${TEXT_EMBEDDINGS_MODEL}
       TEXT_GENERATION_MODEL: ${TEXT_GENERATION_MODEL}
    tty: true
    restart: on-failure
    ports:
      - '11434:11434'
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=4
    command: serve
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama: