version: '3.8'

services:

  ollama:
    build:
      context: ..
      dockerfile: docker/ollama/Dockerfile
    tty: true
    restart: on-failure
    ports:
      - '11434:11434'
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=4
    command: serve
    volumes:
      - ollama:/root/.ollama

  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    tty: true
    restart: on-failure
    ports:
      - '8080:8080'



volumes:
  ollama: