llm:
  default:
    model:
      text:
        embedding:
          name: nomic-embed-text:latest
        generating:
          name: llama3:latest
      image:
        description:
          name: llava:latest
    url: http://localhost:11434
