llm:
  engines:
    - type: ollama
      url: ${OLLAMA_URL:http://localhost:11434}
    - type: open-ai
      url: http://openai:777

  models:
    - engine: ollama
      type: text-embedding
      name: nomic-embed-text:latest
    - engine: ollama
      type: text-generation
      name: llama3:latest
    - engine: ollama
      type: image-description
      name: llava:latest
    - engine: open-ai
      type: text-embedding
      name: test1
 #   - engine: open-ai
 #     type: text-generation
 #     name: test2
 #   - engine: open-ai
 #     type: image-description
 #     name: test3

spring:
  codec:
    max-in-memory-size: 10MB



