llm:
  engines:
    ollama:
      url: ${OLLAMA_URL:http://localhost:11434}
    open-ai:
      url: http://openai:777

  models:
    - engine: ollama
      action: text-embedding
      name: nomic-embed-text:latest
    - engine: ollama
      action: text-generation
      name: llama3:latest
    - engine: ollama
      action: image-description
      name: llava:latest
    - engine: open-ai
      action: text-embedding
      name: test1
 #   - engine: open-ai
 #     action: text-generation
 #     name: test2
 #   - engine: open-ai
 #     action: image-description
 #     name: test3

spring:
  codec:
    max-in-memory-size: 10MB



